name: haitian_casino_flutter
description: "A simple Haitian Casino card game with animations and sounds"

# Prevent accidental publishing
publish_to: 'none'

# Version number
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

# Dependencies required by the app
dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # Audio player for sounds
  audioplayers: ^5.2.1

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Latest recommended lints
  flutter_lints: ^6.0.0

# Flutter-specific settings
flutter:

  # Include Material Icons
  uses-material-design: true

  # Assets to include
  assets:
    - assets/sounds/
